# Navigation
RIGHT       seek  5
LEFT        seek -5
UP          seek  60
DOWN        seek -60
Shift+RIGHT seek  1 exact
Shift+LEFT  seek -1 exact

# Volume
WHEEL_UP    add volume  2
WHEEL_DOWN  add volume -2

# Playback
SPACE       cycle pause
f           cycle fullscreen
m           cycle mute
s           screenshot

# Subtitle
v           cycle sub-visibility
j           cycle sub
J           cycle sub down

# uosc menu
MBTN_RIGHT  script-binding uosc/menu
