[config]

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.fastfetch]
input_path = '~/.config/matugen/templates/fastfetch.jsonc'
output_path = '~/.config/fastfetch/config.jsonc'

[templates.niri-border-gradient]
input_path = '~/.config/matugen/templates/niri-border-gradient.txt'
output_path = '~/.config/niri/dms/border-gradient-colors.txt'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/dms-matugen.toml'
post_hook = 'vicinae theme set dms-matugen 2>/dev/null || true'
